Parte 01: Introdução à classificação

In [ ]:
# features (características)
# 1 sim 0 não
#        pêlo longo?
#        perna curta?
#        faz auau?
porco1 = [0,1,0]
porco2 = [0,1,1]
porco3 = [1,1,0]

cachorro1 = [0,1,1]
cachorro2 = [1,0,1]
cachorro3 = [1,1,1]

# 1 - porco e 0 -  cachorro
train_x = [porco1, porco2, porco3, cachorro1, cachorro2, cachorro3]
train_y = [1,1,1,0,0,0]
# são o x e o y para treinar o modelo. A função é f(x)=y

In [ ]:
#importar estimador
from sklearn.svm import LinearSVC

model = LinearSVC()
#adaptar o modelo às informações
model.fit(train_x, train_y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [ ]:
# trago uma informação nova, um animal desconhecido para o modelo
animal_misterioso = [1,1,1]
#peço ao modelo para (pre)dizer que animal é esse (dentro da classificação que ele conhece)
model.predict([animal_misterioso])
#precisa passar entre [], pq ele espera 2D então a gente passa um array com 3 features
# se []: é esperado um array de duas dimensões, enquanto tivemos apenas uma

array([0])

In [ ]:
#mais teste
misterio1 = [1,1,1]
misterio2 = [1,1,0]
misterio3 = [0,1,1]

teste_x = [misterio1, misterio2, misterio3]
# resposta certa era: [0,1,1]
teste_y = [0,1,1]

In [ ]:
previsoes = model.predict(teste_x)

In [ ]:
previsoes
#o formato é diferentes do testes_classes pq o sklearn usa o numpy

array([0, 1, 0])

In [ ]:
teste_y

[0, 1, 1]

In [ ]:
previsoes == teste_y
#retorna um array do numpy por causa de previsoes

array([ True,  True, False])

In [ ]:
#O número de corretos:
corretos = (previsoes == teste_y).sum()

total=len(teste_x)

taxa_de_acerto1 = corretos/total
print("Taxa de acerto %.2f " % (taxa_de_acerto1*100))

Taxa de acerto 66.67 


In [ ]:
#Funções prontas para trazer a acurácia (taxa de acerto)
from sklearn.metrics import accuracy_score

taxa_de_acerto = accuracy_score(teste_y, previsoes)
#utilizando o placeholder
print("Taxa de acerto: {}%".format(round(taxa_de_acerto*100,2)))

Taxa de acerto: 66.67%
